### 1.Basic exercises using numpy: 

let u = (1, 2, 3, 3, 2, 1)'

In [1]:
import numpy as np

In [2]:
u = np.array([1,2,3,3,2,1]).reshape(-1,1)
u

array([[1],
       [2],
       [3],
       [3],
       [2],
       [1]])

(a) Compute $U = I − \frac{2}{u'u}\times uu'$ (This type of matrix is known as an ‘elementary reflector’ or a ‘Householder transformation.’)

In [3]:
u.shape

(6, 1)

In [4]:
U = np.eye(u.shape[0]) - 2/(u.T @ u) * u @ u.T
U

array([[ 0.92857143, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
        -0.07142857],
       [-0.14285714,  0.71428571, -0.42857143, -0.42857143, -0.28571429,
        -0.14285714],
       [-0.21428571, -0.42857143,  0.35714286, -0.64285714, -0.42857143,
        -0.21428571],
       [-0.21428571, -0.42857143, -0.64285714,  0.35714286, -0.42857143,
        -0.21428571],
       [-0.14285714, -0.28571429, -0.42857143, -0.42857143,  0.71428571,
        -0.14285714],
       [-0.07142857, -0.14285714, -0.21428571, -0.21428571, -0.14285714,
         0.92857143]])

(b) Let C = UU (matrix-matrix multiplication), the matrix product of U and itself. Find the largest and smallest off-diagonal elements of C.


$C$ should be an identity matrix! Proof: $C=U^2=I+\frac{4}{u'uu'u}u(u'u)u'-\frac{2\times2}{u'u}uu'=I$. QED.

In [5]:
C = U @ U
C # This C matrix should be an identity matrix. All weird elements here appear because of round-off errors!

array([[ 1.00000000e+00, -2.46401539e-17, -5.55111512e-17,
        -4.38991247e-17, -2.77555756e-17, -1.92589708e-17],
       [-2.46401539e-17,  1.00000000e+00, -7.59030027e-17,
        -1.11022302e-16, -4.48195902e-17, -2.77555756e-17],
       [-5.55111512e-17, -7.59030027e-17,  1.00000000e+00,
        -7.22211406e-17, -1.11022302e-16, -4.48903953e-17],
       [-4.38991247e-17, -1.11022302e-16, -7.22211406e-17,
         1.00000000e+00, -8.97807905e-17, -8.32667268e-17],
       [-2.08166817e-17, -5.55111512e-17, -9.71445147e-17,
        -5.55111512e-17,  1.00000000e+00, -4.16333634e-17],
       [-1.38777878e-17, -2.77555756e-17, -5.55111512e-17,
        -8.32667268e-17, -4.16333634e-17,  1.00000000e+00]])

In [6]:
# largest off- diagonal elements of C
from copy import deepcopy
C_tmp = deepcopy(C)
np.fill_diagonal(C_tmp,float('-inf'))
np.max(C_tmp) # should be zero actually! It is non-zero here because of round-off errors!

-1.3877787807814457e-17

In [7]:
# smallest off- diagonal elements of C
from copy import deepcopy
C_tmp = deepcopy(C)
np.fill_diagonal(C_tmp,float('inf'))
np.min(C_tmp)# should be zero actually! It is non-zero here because of round-off errors!

-1.1102230246251565e-16

(c) Find the largest and smallest diagonal elements of C.

In [8]:
# largest diagonal element of C
np.max(np.diag(C))

1.0

In [9]:
# smallest diagonal element of C
np.min(np.diag(C)) # It is actually 1. this phenomenon happens because of round-off errors.

0.9999999999999998

(d) Compute Uu. (matrix-vector multiplication)

In [10]:
Uu = U @ u
Uu

array([[-1.],
       [-2.],
       [-3.],
       [-3.],
       [-2.],
       [-1.]])

(e) Compute the scalar $\max_i \sum_j|U_{ij} |$

In [34]:
max(np.sum(abs(U),axis=1))

2.2857142857142856

(f) Print the third row of $U$.

In [36]:
print(U[2])

[-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]


(g) Print the elements of the second column below the diagonal.

In [37]:
print(U[2:,1])

[-0.42857143 -0.42857143 -0.28571429 -0.14285714]


(h) Let $A$ be the first three columns of $U$. Compute $P = AA'$ .

In [41]:
A = U[:,0:3]
P = A @ A.T
P

array([[ 9.28571429e-01, -1.42857143e-01, -2.14285714e-01,
        -3.54025199e-17, -2.88884563e-17, -1.44442281e-17],
       [-1.42857143e-01,  7.14285714e-01, -4.28571429e-01,
        -1.52938886e-17, -2.26576127e-18, -1.13288064e-18],
       [-2.14285714e-01, -4.28571429e-01,  3.57142857e-01,
        -4.07837029e-17, -4.30494642e-17, -2.15247321e-17],
       [-3.54025199e-17, -1.52938886e-17, -4.07837029e-17,
         6.42857143e-01,  4.28571429e-01,  2.14285714e-01],
       [-2.88884563e-17, -2.26576127e-18, -4.30494642e-17,
         4.28571429e-01,  2.85714286e-01,  1.42857143e-01],
       [-1.44442281e-17, -1.13288064e-18, -2.15247321e-17,
         2.14285714e-01,  1.42857143e-01,  7.14285714e-02]])

(i) Show that $P$ is idempotent by recomputing (e) with $ P P − P$.

Proof: $U=I$ actually. So $A'A=I_3$. $PP=AA'AA'=AI_3A'=AA'=P$.QED

In [43]:
result = P@P-P
np.allclose(result, np.zeros(result.shape))

True

Your demand is confusing... OK. I will do as you command...

In [51]:
max(np.sum(abs(P@P-P),axis=1))

2.43852557194454e-16

That means all elements are super close to zero, right? So that gets proved.

(j) Let $B$ be the last three columns of $U$. Compute $Q = BB'$ .

In [46]:
B=U[:,-3:]
Q=B@B.T
Q

array([[ 7.14285714e-02,  1.42857143e-01,  2.14285714e-01,
        -2.38967009e-17, -7.25751658e-18, -8.21338462e-18],
       [ 1.42857143e-01,  2.85714286e-01,  4.28571429e-01,
        -4.77934019e-17, -1.45150332e-17, -1.64267692e-17],
       [ 2.14285714e-01,  4.28571429e-01,  6.42857143e-01,
        -2.83220159e-17, -2.00378263e-17, -2.46401539e-17],
       [-2.38967009e-17, -4.77934019e-17, -2.83220159e-17,
         3.57142857e-01, -4.28571429e-01, -2.14285714e-01],
       [-7.25751658e-18, -1.45150332e-17, -2.00378263e-17,
        -4.28571429e-01,  7.14285714e-01, -1.42857143e-01],
       [-8.21338462e-18, -1.64267692e-17, -2.46401539e-17,
        -2.14285714e-01, -1.42857143e-01,  9.28571429e-01]])

(k) Show that $Q$ is idempotent by recomputing (e) with $QQ − Q$.

Proof: $U=I$ actually. So $B'B=I_3$. $QQ=BB'BB'=BI_3B'=BB'=Q$.QED

In [47]:
result = Q@Q-Q
np.allclose(result, np.zeros(result.shape))

True

Your demand is confusing... OK. I will do as you command...

In [48]:
max(np.sum(abs(Q@Q-Q),axis=1))

3.039660360150381e-16

In [ ]:
(l) Compute P + Q

That means all elements are super close to zero, right? So that gets proved.

(l) Compute P + Q

In [52]:
P + Q

array([[ 1.00000000e+00, -2.77555756e-17, -5.55111512e-17,
        -5.92992209e-17, -3.61459728e-17, -2.26576127e-17],
       [-2.77555756e-17,  1.00000000e+00, -5.55111512e-17,
        -6.30872905e-17, -1.67807944e-17, -1.75596499e-17],
       [-5.55111512e-17, -5.55111512e-17,  1.00000000e+00,
        -6.91057189e-17, -6.30872905e-17, -4.61648860e-17],
       [-5.92992209e-17, -6.30872905e-17, -6.91057189e-17,
         1.00000000e+00, -1.11022302e-16, -5.55111512e-17],
       [-3.61459728e-17, -1.67807944e-17, -6.30872905e-17,
        -1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [-2.26576127e-17, -1.75596499e-17, -4.61648860e-17,
        -5.55111512e-17,  0.00000000e+00,  1.00000000e+00]])

### 2. 

Read in the matrix in the file ‘oringp.dat’ (available on Piazza) on the failure of O-rings leading to the Challenger disaster. 

The columns are flight number, date, number of O-rings, number failed, and temperature at launch. 

Compute the correlation between number of failures and temperature at launch, deleting the last, missing observation (the disaster).

In [57]:
import pandas as pd

In [67]:
df = pd.read_csv('oringp.dat', parse_dates=[2], sep='\s+', header=None, names=['flight', 'date', 'num_orings', 'num_failures', 'temp'])
df

flight      date num_orings  num_failures  temp
0       1   4/12/81          6           0.0    66
1       2  11/12/81          6           1.0    70
2       3   3/22/82          6           0.0    69
3       5  11/11/82          6           0.0    68
4       6   4/04/83          6           0.0    67
5       7   6/18/83          6           0.0    72
6       8   8/30/83          6           0.0    73
7       9  11/28/83          6           0.0    70
8    41-B   2/03/84          6           1.0    57
9    41-C   4/06/84          6           1.0    63
10   41-D   8/30/84          6           1.0    70
11   41-G  10/05/84          6           0.0    78
12   51-A  11/08/84          6           0.0    67
13   51-C   1/24/85          6           3.0    53
14   51-D   4/12/85          6           0.0    67
15   51-B   4/29/85          6           0.0    75
16   51-G   6/17/85          6           0.0    70
17   51-F   7/29/85          6           0.0    81
18   51-I   8/27/85          6           0.0    76
19   51-J  10/03/85          6           0.0    79
20   61-A  10/30/85          6           2.0    75
21   61-B  11/26/85          6           0.0    76
22   61-C   1/12/86          6           1.0    58
23   61-I   1/28/86          6           NaN    31

In [69]:
df = df.dropna()
df

flight      date num_orings  num_failures  temp
0       1   4/12/81          6           0.0    66
1       2  11/12/81          6           1.0    70
2       3   3/22/82          6           0.0    69
3       5  11/11/82          6           0.0    68
4       6   4/04/83          6           0.0    67
5       7   6/18/83          6           0.0    72
6       8   8/30/83          6           0.0    73
7       9  11/28/83          6           0.0    70
8    41-B   2/03/84          6           1.0    57
9    41-C   4/06/84          6           1.0    63
10   41-D   8/30/84          6           1.0    70
11   41-G  10/05/84          6           0.0    78
12   51-A  11/08/84          6           0.0    67
13   51-C   1/24/85          6           3.0    53
14   51-D   4/12/85          6           0.0    67
15   51-B   4/29/85          6           0.0    75
16   51-G   6/17/85          6           0.0    70
17   51-F   7/29/85          6           0.0    81
18   51-I   8/27/85          6           0.0    76
19   51-J  10/03/85          6           0.0    79
20   61-A  10/30/85          6           2.0    75
21   61-B  11/26/85          6           0.0    76
22   61-C   1/12/86          6           1.0    58

In [73]:
# Convert to numeric types
df['num_failures'] = pd.to_numeric(df['num_failures'])
df['tmp'] = pd.to_numeric(df['temp'])

# Correlation
correlation = df['num_failures'].corr(df['temp'])
correlation

-0.5613284258418356

### 3.Consider the mixed effect model
$$y_i=x_i'\beta+z_i'\gamma+\epsilon_i,\ i=1,\cdots,n$$

where $\epsilon_i \sim N(0, \sigma_0^2)$ are independent normal errors, $\beta\in\mathbf{R}^p$ are fixed effects, $\gamma\in\mathbf{R}^q$ are random effects assumed to be $N(0_q,\sigma_1^2I_q)$, $\gamma$ and $\epsilon_i$ are independent. For simplicity, assume $\mu_i=x_i'\beta$. Let $y = (y_1, \cdots, y_n)'$, $\mu = (\mu_1,\cdots, \mu_n)'$, $Z = (z_1,\cdots , z_n)'$, then $y \in\mathbf{R}^n$, $\mu\in\mathbf{R}^n$, $Z \in \mathbf{R}^{n\times q}$, and $y\sim\ N(\mu, \sigma_1^2ZZ'+\sigma_0^2I_n)$. The log-density function is given by
$$-\frac{n}{2}\log(2\pi)-\frac{1}{2}\log(\det(\sigma_1^2ZZ'+\sigma_0^2I_n))-\frac{1}{2}(y-\mu)'(\sigma_1^2ZZ'+\sigma_0^2I_n)^{-1}(y-\mu).$$


Please write a function, call it `dmvnorm_lowrank(y, mu, Z,sigma0,sigma1, log = FALSE)` that evaluates the (log)-density function at a given $y\in\mathbf{R}^n$. Choose values for $n(> 5)$ and $q(> 3)$, test your function on simulated data.

Notes: 

1) When `log = TRUE`, your function should calculate the log likelihood; when `log = FALSE`, your function should calculate the original likelihood function. The default uses `log = FALSE`. 

2) Use the `np.random.seed` function before generating data from a random distribution.

In [101]:
def dmvnorm_lowrank(y, mu, Z, sigma0, sigma1, log=False):
    n = mu.shape[0]
    # The most trivial way to implement this. It is bad in time complexity, though.
    log_dens = -n/2*np.log(2*np.pi)\
    -1/2*np.log(np.linalg.det(sigma1**2 * Z @ Z.T + sigma0**2 * np.eye(n)))\
    -1/2*(y-mu).T @ np.linalg.inv(sigma1**2 * Z @ Z.T + sigma0**2 * np.eye(n)) @ (y-mu)
    return log_dens if log else np.exp(log_dens)

Define $X:=(x_1,\cdots,x_n)'$. 

Then $\mu=X\beta$.

In [123]:
# Set random seed to be 1234
np.random.seed(1234)
# Initialization of basic parameters
n = 7
q = 4
p = 5 # needs to be smaller than n
sigma0 = 5
sigma1 = 10
# Ramdomly generate eps and gamma
eps = np.random.normal(0, sigma0, n) # Trivial. Notice that sigma here is standard deviation!
gamma = np.random.normal(0, sigma1, q) # The multi-normal form indicates all gamma are iid from N(0,sigma1^2)
# Randomly generate some X, Z, and beta
X = np.random.normal(size=(n, p))
beta = np.random.normal(size=p)
Z = np.random.normal(size=(n, q))
# Compute mu and y w.r.t X, beta, Z, gamma, and eps
mu = X @ beta
y = mu + Z @ gamma + eps

In [124]:
# Compute log-density
log_like = dmvnorm_lowrank(y, mu, Z, sigma0, sigma1, log=True)
print(log_like)

-27.64578963590802


In [125]:
log_like = dmvnorm_lowrank(y, mu, Z, sigma0, sigma1)
print(log_like)

9.853399997297273e-13
